create table system_item(
    id varchar primary key,
    url varchar(255),
    date varchar(255) not null,
    type int not null,
    size int,
    parent_id varchar(255) references system_item(id) on delete cascade
);

create table system_item_history(
    history_id int generated by default as identity primary key,
    id varchar(255) references system_item(id) on delete cascade,
    url varchar(255),
    date varchar(255) not null,
    type int not null,
    size int,
    parent_id varchar(255)
);